[package]
name = "phoenix_wrust"
version = "0.1.0"
edition = "2021"
authors = ["me"]
license = "MIT OR Apache-2.0"

# [[bin]]
# name = "phoenix_wrust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# erupt = "=0.22.0+204"

[dependencies]
image = "0.23"
log = "0.4"
tobj = "3"
# russimp = "1.0.3"

ash-window = "0.11.0"
winit = "=0.26"
gpu-alloc = "0.5.3"
gpu-alloc-ash = "0.5.0"
getset = "0.1.2"
# rental = "0.5.6"
# ouroboros = "0.15.3"
shaderc = "0.8.0"
# regex = "=1.1.0"
# regex = "1.6.0"
regex = "=1.1.0"
spirv-reflect = "0.2.3"
arrayvec = "0.7"
# default-args = "1.0.0"
# duang = "0.1.2"
generational-arena = "0.2.8"
# bumpalo = "3.11.0"
# renderdoc = "0.10.1"
smallvec = "1.9.0"
nalgebra-glm = "0.17.0"

gltf = "1.0.0"
imgui-rs-vulkan-renderer = "1.5.0"


# egui = "0.19.0"
# egui = "0.19.0"

egui = "0.16.1"

ash = "=0.37.0+1.3.209"
# ash = { version = "0.37.0", features = ["linked", "debug"]}

# egui_winit_ash_integration
# egui-winit-ash-integration = "0.2.0"
egui-winit-ash-integration = { git = "https://github.com/simplerr/egui-winit-ash-integration" } # "0.2.0"
# gpu-allocator = "0.19.0"
gpu-allocator = "0.18.0"


# russimp = {version = "=1.0.4", features = ["prebuilt", "static-link"]}
# russimp = {git = "https://github.com/wrightwriter/russimp", features = ["prebuilt"]}


# russimp-sys = "=1.0.3"
# russimp = {git= "https://github.com/jkvargas/russimp"}

stb_image = "0.2.4"




# egui_winit_ash_integration = {git="https://github.com/MatchaChoco010/egui-winit-ash-integration"}
# renderdoc = {git="https://github.com/Jengamon/renderdoc-rs"}

renderdoc = {git="https://github.com/wrightwriter/renderdoc-rs"}


notify = "5.0.0"
spirv-tools = "0.8.0"

[profile.release]
debug = 1